export const studyDatas = [
  {
    id: 1,
    name: "왕초보 스터디",
    leader: "유태승",
    time: "수요일 23시",
    member: "6",
  },
  {
    id: 2,
    name: "나야, 리액트",
    leader: "김건휘",
    time: "월요일 23시",
    member: "6",
  },
  {
    id: 3,
    name: "자스핑",
    leader: "문성희",
    time: "목요일 23시",
    member: "4",
  },
  {
    id: 4,
    name: "웹부스 파캉파캉",
    leader: "이예림",
    time: "목요일 20시",
    member: "5",
  },
  {
    id: 5,
    name: "호기심스",
    leader: "박채연",
    time: "화요일 23시",
    member: "6",
  },
  {
    id: 6,
    name: "C박과 함께하는 CSS & 퍼블리싱 스터디",
    leader: "임화랑",
    time: "목요일 23시",
    member: "8",
  },
  {
    id: 7,
    name: "미라클 모닝 알고리즘 스터디",
    leader: "공준혁",
    time: "금요일 10시",
    member: "10",
  },
];
